name: Build for Windows
on:
  push:
    branches:
    - "develop"
  pull_request:
    branches:
    - "main"
  workflow_dispatch:
env:
  BOOST_VERSION: "1.79.0"
  QT_VERSION: "5.15.2"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install QT
      uses: jurplel/install-qt-action@v2
      with:
        host: windows
        target: "desktop"
        version: ${{ env.QT_VERSION }}
        install-deps: "true"
    - name: Install Boost
      id: install-boost
      uses: MarkusJx/install-boost@v2.3.0
      with:
        boost_version: ${{ env.BOOST_VERSION }}
        toolset: msvc
    - name: Build fritzing
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat" -test