name: Build for Windows
on:
  push:
    branches:
    - "develop"
  pull_request:
    branches:
    - "main"
  workflow_dispatch:
env:
  BOOST_VERSION: "1.79.0"
  QT_VERSION: "5.15.2"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
    - name: Install QT
      uses: jurplel/install-qt-action@v2
      with:
        host: windows
        target: "desktop"
        version: ${{ env.QT_VERSION }}
        install-deps: "true"
    - name: Install Boost
      id: install-boost
      uses: MarkusJx/install-boost@v2.3.0
      with:
        boost_version: ${{ env.BOOST_VERSION }}
        toolset: msvc
    - name: Build fritzing
      shell: cmd
      run: |
        call "%VSINSTALLDIR%\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
        call "%VSINSTALLDIR%\Common7\Tools\VsDevCmd.bat" -test